-- Migration: add order_status column and tracking
-- File: backend/migrations/20240627_add_order_status_and_tracking.sql

-- 1. Add order_status column to orders (if not exists)
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS order_status TEXT NOT NULL DEFAULT 'pending';

-- 2. Create order_status_updates table to keep a history of status changes
CREATE TABLE IF NOT EXISTS order_status_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  previous_status TEXT NOT NULL,
  new_status TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Function to update order status atomically and insert into history
CREATE OR REPLACE FUNCTION public.update_order_status(p_order_id TEXT, p_new_status TEXT)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_current_status TEXT;
BEGIN
  -- Get current status with row lock
  SELECT order_status INTO v_current_status FROM orders WHERE order_id = p_order_id FOR UPDATE;

  IF v_current_status IS NULL THEN
    RAISE EXCEPTION 'Order % not found', p_order_id;
  END IF;

  -- Update status
  UPDATE orders SET order_status = p_new_status, updated_at = now() WHERE order_id = p_order_id;

  -- Insert history record
  INSERT INTO order_status_updates (order_id, previous_status, new_status)
  VALUES (p_order_id, v_current_status, p_new_status);

  -- Notify Supabase Realtime (uses pg_notify under the hood)
  PERFORM pg_notify('order_status_change', json_build_object('order_id', p_order_id, 'new_status', p_new_status)::text);
END;
$$;

-- Grant execute permission to anon and authenticated roles
GRANT EXECUTE ON FUNCTION public.update_order_status(TEXT, TEXT) TO anon, authenticated;
